package Views.Kasiyer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Entities.SatisToplam;
import Entities.Sepet;
import Entities.Urunler;
import Models.SatisDAL;
import Models.SepetDAL;
import Models.UrunlerDAL;
import Views.AnaEkran;
import java.awt.event.FocusListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ZEYNEP
 */
public class frmUrunSatis extends javax.swing.JFrame {

    DefaultTableModel model, mod;
      

    public static String no = "";
    UrunlerDAL islemler = new UrunlerDAL();
    Urunler urun = new Urunler();
     List<Urunler> urunList = new ArrayList<>();
    SatisDAL satis = new SatisDAL();
     SatisToplam toplam = new SatisToplam();
    List<SatisToplam> satisList = new ArrayList<>();
    SepetDAL sepetI = new SepetDAL();
    List<Sepet> sepetList = new ArrayList<>();

    double miktar, fiyat, sonuc;

    public static float GeciciTutar = 0;
    public static String tutar3 = "";

    /**
     * Creates new form frmUrunSatis
     */
    public frmUrunSatis() {
        initComponents();

        mod = new DefaultTableModel();
        mod.fireTableDataChanged();
        model = new DefaultTableModel();
        model.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtuNo = new javax.swing.JTextField();
        bHesapla = new javax.swing.JButton();
        txtTutar = new javax.swing.JTextField();
        bSepeteEkle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bSatisiTamamla = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bSepetiHesapla = new javax.swing.JButton();
        bYeniSatis = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        UrunTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtuMiktar = new javax.swing.JTextField();
        LUrunAdi = new javax.swing.JLabel();
        LMarka = new javax.swing.JLabel();
        LFiyat = new javax.swing.JLabel();
        Odeme = new javax.swing.JComboBox<>();
        txtToplamTutar = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableSepet = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SATIŞ");
        setBounds(new java.awt.Rectangle(250, 120, 0, 0));
        setLocation(new java.awt.Point(290, 80));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 110, 123));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SATIŞ");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ürün Adı        :");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ürün Miktari  :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ürün Marka   :");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fiyat           :");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tutar          :");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Ürün No       :");

        txtuNo.setBackground(new java.awt.Color(171, 183, 183));
        txtuNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuNoActionPerformed(evt);
            }
        });

        bHesapla.setBackground(new java.awt.Color(75, 119, 190));
        bHesapla.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        bHesapla.setForeground(new java.awt.Color(255, 255, 255));
        bHesapla.setText("Hesapla");
        bHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHesaplaActionPerformed(evt);
            }
        });

        txtTutar.setBackground(new java.awt.Color(171, 183, 183));

        bSepeteEkle.setBackground(new java.awt.Color(75, 119, 190));
        bSepeteEkle.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        bSepeteEkle.setForeground(new java.awt.Color(255, 255, 255));
        bSepeteEkle.setText("Sepete Ekle");
        bSepeteEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSepeteEkleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Toplam Tutar :");

        bSatisiTamamla.setBackground(new java.awt.Color(75, 119, 190));
        bSatisiTamamla.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        bSatisiTamamla.setForeground(new java.awt.Color(255, 255, 255));
        bSatisiTamamla.setText("Satışı Tamamla");
        bSatisiTamamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSatisiTamamlaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ödeme        :");

        bSepetiHesapla.setBackground(new java.awt.Color(75, 119, 190));
        bSepetiHesapla.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        bSepetiHesapla.setForeground(new java.awt.Color(255, 255, 255));
        bSepetiHesapla.setText("Sepeti Hesapla");
        bSepetiHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSepetiHesaplaActionPerformed(evt);
            }
        });

        bYeniSatis.setBackground(new java.awt.Color(75, 119, 190));
        bYeniSatis.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        bYeniSatis.setForeground(new java.awt.Color(255, 255, 255));
        bYeniSatis.setText("Yeni Satış");
        bYeniSatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bYeniSatisActionPerformed(evt);
            }
        });

        UrunTable.setBackground(new java.awt.Color(171, 183, 183));
        UrunTable.setFont(new java.awt.Font("Comic Sans MS", 1, 8)); // NOI18N
        UrunTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        UrunTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UrunTableMouseClicked(evt);
            }
        });
        UrunTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UrunTableKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(UrunTable);
        if (UrunTable.getColumnModel().getColumnCount() > 0) {
            UrunTable.getColumnModel().getColumn(2).setResizable(false);
            UrunTable.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sepet :");

        txtuMiktar.setBackground(new java.awt.Color(171, 183, 183));
        txtuMiktar.setText("1");
        txtuMiktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuMiktarActionPerformed(evt);
            }
        });

        LUrunAdi.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        LUrunAdi.setForeground(new java.awt.Color(255, 255, 255));
        LUrunAdi.setText("urun");

        LMarka.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        LMarka.setForeground(new java.awt.Color(255, 255, 255));
        LMarka.setText("marka");

        LFiyat.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        LFiyat.setForeground(new java.awt.Color(255, 255, 255));
        LFiyat.setText("fiyat");

        Odeme.setBackground(java.awt.Color.gray);
        Odeme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nakit", "Kart" }));

        txtToplamTutar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtToplamTutar.setForeground(new java.awt.Color(255, 255, 255));

        TableSepet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        TableSepet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSepetMouseClicked(evt);
            }
        });
        TableSepet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableSepetKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(TableSepet);
        if (TableSepet.getColumnModel().getColumnCount() > 0) {
            TableSepet.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ana-sayfa2.png"))); // NOI18N
        jLabel14.setText("Ana Sayfa");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LFiyat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(bSepeteEkle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                            .addComponent(txtTutar, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bHesapla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 61, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LMarka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Odeme, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtuNo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtuMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LUrunAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bYeniSatis, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtToplamTutar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSatisiTamamla, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bSepetiHesapla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Odeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtuNo))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LUrunAdi))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LMarka))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtuMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LFiyat))
                        .addGap(7, 7, 7)
                        .addComponent(bHesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSepetiHesapla)
                            .addComponent(jLabel2)
                            .addComponent(txtToplamTutar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bSatisiTamamla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bYeniSatis)
                        .addGap(8, 8, 8)))
                .addComponent(bSepeteEkle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void UrunTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UrunTableKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_UrunTableKeyReleased

    private void UrunTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UrunTableMouseClicked
        // TODO add your handling code here:

        int selectedrow = UrunTable.getSelectedRow();

        txtuNo.setText(model.getValueAt(selectedrow, 2).toString());
        LUrunAdi.setText(model.getValueAt(selectedrow, 3).toString());
        LMarka.setText(model.getValueAt(selectedrow, 4).toString());
        txtuMiktar.setText(model.getValueAt(selectedrow, 5).toString());
        LFiyat.setText(model.getValueAt(selectedrow, 6).toString());
        txtToplamTutar.setText(model.getValueAt(selectedrow, 7).toString());
        Odeme.setSelectedItem(model.getValueAt(selectedrow, 8).toString());


    }//GEN-LAST:event_UrunTableMouseClicked

    private void bHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHesaplaActionPerformed
        // TODO add your handling code here:

        miktar = Float.parseFloat(txtuMiktar.getText());
        fiyat = Float.parseFloat(LFiyat.getText());
        sonuc = miktar * fiyat;
        txtTutar.setText(String.valueOf(sonuc));
       


    }//GEN-LAST:event_bHesaplaActionPerformed
    public void SepetGetir() {
        mod = new DefaultTableModel(new String[]{"Urun adı", "urun Marka", "urun miktar", "urun fiyar", "toplam"}, 0);

        sepetList = sepetI.getAll();

        for (Sepet s : sepetList) {

            mod.addRow(new Object[]{s.getUrunAdi(), s.getUrunMarka(), s.getMiktar(), s.getFiyat(), s.getTop()});
            TableSepet.setModel(mod);

        }
        sepetList.clear();

//TRUNCATE TABLE `sepet` tabloyu basoltmak için kullamılacak sql sorgusu
    }

    public void sepetEkle() {

        Sepet sepet = new Sepet();
        sepet.setUrunAdi(LUrunAdi.getText());
        sepet.setUrunMarka(LMarka.getText());
        sepet.setMiktar(Integer.parseInt(txtuMiktar.getText()));
        sepet.setFiyat(Float.parseFloat(LFiyat.getText()));
        sepet.setTop(Float.parseFloat(txtTutar.getText()));
        sepetI.create(sepet);
        tabloyaEkle();
        islemler.delete2(txtuNo.getText());
      
    }

    public void sepetiHesapla() {
        try {
            TableSepet.setRowSelectionInterval(0, 0);
            float satis = 0;
            for (int i = 0; i < mod.getRowCount(); i++) {
                String yeni = TableSepet.getValueAt(i, 4).toString();

                satis += Float.parseFloat(yeni);
                txtToplamTutar.setText(String.valueOf(satis));
                tutar3 = String.valueOf(satis);
            }

        } catch (Exception e) {
            System.out.println("hata: " + e);
        }

    }
    private void bSepeteEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSepeteEkleActionPerformed
        sepetEkle();
        SepetGetir();
        tabloGetir();
    }//GEN-LAST:event_bSepeteEkleActionPerformed

    private void bSepetiHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSepetiHesaplaActionPerformed

        sepetiHesapla();
      

    }//GEN-LAST:event_bSepetiHesaplaActionPerformed

    private void bSatisiTamamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSatisiTamamlaActionPerformed
      
        MusteriFis fis = new MusteriFis();
        this.setVisible(false);
        fis.setVisible(true);
   
        


    }//GEN-LAST:event_bSatisiTamamlaActionPerformed

    private void bYeniSatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bYeniSatisActionPerformed
        // TODO add your handling code here:
        sepetI.TabloyuSıfırla();
        frmUrunSatis frmSatis = new frmUrunSatis();

        frmSatis.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_bYeniSatisActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        SepetGetir();
        tabloGetir();
    }//GEN-LAST:event_formWindowOpened

    private void txtuNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuNoActionPerformed
        bilgiGetir();//enter basınca geiyor degerler
    }//GEN-LAST:event_txtuNoActionPerformed

    private void txtuMiktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuMiktarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuMiktarActionPerformed

    private void TableSepetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSepetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableSepetMouseClicked

    private void TableSepetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableSepetKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TableSepetKeyReleased

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        AnaEkran anaEkranDon = new AnaEkran();
        anaEkranDon.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked
    public void bilgiGetir() {//*uru numarasıgırılınce bılgı getrısın
        Urunler urun = new Urunler();
        urun = islemler.findByID(txtuNo.getText());

        LUrunAdi.setText(urun.getUrunAdi());
        LMarka.setText(urun.getUrunMarka());
        LFiyat.setText(urun.getUrunSatis().toString());

    }

    public void tabloyaEkle() {//sisteme girilen veriyi direk kayıt eder.
         Date tarih = new Date();
     
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        System.out.println();
        try {
          
            Urunler urun = new Urunler();
            urun = islemler.findByID(txtuNo.getText());
            SatisToplam toplam = new SatisToplam();
            toplam.setUrunNo(txtuNo.getText());
            toplam.setKasaNo(frmKasaSec.no);
            toplam.setUrunAdi(LUrunAdi.getText());
            toplam.setUrunMarka(LMarka.getText());
            toplam.setMiktar(Integer.parseInt(txtuMiktar.getText()));
            toplam.setUrunAlis(urun.getUrunAlis());
            toplam.setUrunSatis(Float.parseFloat(LFiyat.getText()));
            toplam.setOdemeYontemi(Odeme.getSelectedItem().toString());
            toplam.setSatisToplam(Float.parseFloat(txtTutar.getText()));
            toplam.setTarih(df.format(tarih));

            satis.create(toplam);
        } catch (Exception e) {
            System.out.println("bir hata meydan geldi" + e);
        }

    }

    public void tabloGetir() {

        model = new DefaultTableModel(new String[]{"Satis ID", "Kasa No", "UrunNo ", "Ad", "Marka", "Miktar", "Fiyat", "Satis Toplam", "Odeme Yontemi","Tarih"}, 0);///durumda enum kullanımı kodda doğru yazdık mı acaba ona bakacam bir eksık var tamamlımw

        satisList = satis.getAll();

        for (SatisToplam top : satisList) {
            model.addRow(new Object[]{top.getSatisId(), top.getKasaNo(), top.getUrunNo(), top.getUrunAdi(), top.getUrunMarka(), top.getMiktar(), top.getUrunSatis(), top.getSatisToplam(), top.getOdemeYontemi(),top.getTarih()});

            UrunTable.setModel(model);
        }
        satisList.clear();

    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUrunSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUrunSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUrunSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUrunSatis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUrunSatis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LFiyat;
    private javax.swing.JLabel LMarka;
    private javax.swing.JLabel LUrunAdi;
    private javax.swing.JComboBox<String> Odeme;
    private javax.swing.JTable TableSepet;
    private javax.swing.JTable UrunTable;
    private javax.swing.JButton bHesapla;
    private javax.swing.JButton bSatisiTamamla;
    private javax.swing.JButton bSepeteEkle;
    private javax.swing.JButton bSepetiHesapla;
    private javax.swing.JButton bYeniSatis;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel txtToplamTutar;
    private javax.swing.JTextField txtTutar;
    private javax.swing.JTextField txtuMiktar;
    private javax.swing.JTextField txtuNo;
    // End of variables declaration//GEN-END:variables


}
